name: Snyk Security
on: [push, pull_request]
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - name: Snyk Code Test
        continue-on-error: true
        run: snyk code test --org=${{ secrets.SNYK_ORG }} --json > snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload JSON file
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk-report.json
